spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  thymeleaf:
    cache: false
    prefix: /templates
  mail:
    host: smtp.qq.com
    username: yyy
    #授权码
    password: xxx
    # 25，465，587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp.auth: true
        smtp.starttls.enable: true
        smtp.starttls.required: true